### ISSUE TITLE
Migrate to Kotlin 1.9.23 and Gradle 8

### ISSUE THREAD

**Issue by josdem** [josdem/fruitypedia#56]
As **developer**, I want to update to Java 21 and Gradle 8.5 **so that** I can use the latest of versions.

**Acceptance Criteria**
- I am able to see Kotlin 1.9.20 in the configuration files
- I can see Gradle 8.5 in the configuration files
- All tests are passing

**References**
- https://docs.gradle.org/current/userguide/compatibility.html

**Comment by MJJacobs01** [comment]
Good evening,

Can I work on this one?

**Comment by josdem** [comment]
Hi @MJJacobs01 absolutely, I assigned this ticket to you. Let me know if any questions. 

> Good evening,
> 
> Can I work on this one?

Hi @MJJacobs01 absolutely, I assigned this ticket to you. Let me know if any questions.

**Comment by MJJacobs01** [comment]
Good morning,

Just to clarify, you specifically want Kotlin version 1.9.20, so I should not upgrade it to 1.9.23?

**Comment by josdem** [comment]
PR merged, all tests passing: https://github.com/josdem/fruitypedia/actions/runs/9094256755
